// Generated by CoffeeScript 1.6.2
(function() {
  window.checkName = function() {
    this.$(".name-alert").hide();
    if (this.$("#newName").val() === "") {
      this.$(".name-alert.alert-danger").show(200);
      return false;
    } else {
      this.$(".name-alert.alert-success").show(200);
      return true;
    }
  };

  window.checkDate = function() {
    var dayObj, inpDate, validFormat;

    this.$(".date-alert").hide();
    if (this.$("#newDate").val() === "") {
      this.$(".date-alert.alert-danger").text("You can`t add task with no date");
      this.$(".date-alert.alert-danger").show(200);
      return false;
    }
    validFormat = /^\d{2}\.\d{2}\.\d{4}$/;
    if (!validFormat.test(this.$("#newDate").val())) {
      this.$(".date-alert.alert-danger").text("Wrong date format (dd.mm.yyyy). Reenter date or use datepicker.");
      this.$(".date-alert.alert-danger").show(200);
      return false;
    }
    inpDate = this.$("#newDate").val().split(".").map(Number);
    inpDate[1]--;
    dayObj = new Date(inpDate[2], inpDate[1], inpDate[0]);
    if ((dayObj.getMonth() !== inpDate[1]) || (dayObj.getDate() !== inpDate[0]) || (dayObj.getFullYear() !== inpDate[2])) {
      this.$(".date-alert.alert-danger").text("Impossible date, like 30-th of Febrary. Reenter date or use datepicker.");
      this.$(".date-alert.alert-danger").show(200);
      return false;
    }
    this.$(".date-alert.alert-success").show(200);
    return true;
  };

}).call(this);
