// Generated by CoffeeScript 1.6.2
(function() {
  window.Router = Backbone.Router.extend({
    routes: {
      "": "showAll",
      "all": "showAll",
      "done": "showDone",
      "notdone": "showNotDone"
    },
    initialize: function() {
      return Backbone.history.start();
    },
    showAll: function() {
      tasks_view.changeViewType("all");
      return this.toggleActiveMenuItem("All Tasks");
    },
    showDone: function() {
      tasks_view.changeViewType("done");
      return this.toggleActiveMenuItem("Done");
    },
    showNotDone: function() {
      tasks_view.changeViewType("notDone");
      return this.toggleActiveMenuItem("Not Done");
    },
    toggleActiveMenuItem: function(text) {
      var i, _i, _len, _ref, _results;

      _ref = $(".navbar-right li");
      _results = [];
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        i = _ref[_i];
        if ($(i).text() === text) {
          _results.push($(i).addClass("active"));
        } else {
          _results.push($(i).removeClass("active"));
        }
      }
      return _results;
    }
  });

}).call(this);
